### ISSUE TITLE
<!-- BEGIN object --> @key and @value <!-- END Object -->

### ISSUE THREAD

**Issue by akhoury** [psychobunny/templates.js#19]
it would be nice if we can iterate over an object, kind of what `$.each` support, and within each iteration expose the `@key` and the `@value` of the context, or maybe just `@key` and `this`

**Comment by psychobunny** [comment]
One thing I worry about in NodeBB context is that the order is not guaranteed. Cold load might have one order while ajaxify (client-side loading) could have another, as opposed to how arrays work.

This is actually quite easy for me to implement, but I think that maybe something like this might be better off as a helper instead.

Pinging @barisusakli as well.

**Comment by akhoury** [comment]
that's fine, you only have to guarantee order if the 1st arg is an "Array" like object or a collection; if it has a `length` property i.e. Array, arguments, NodeList etc. aka 

`Object.keys` does not guarantee order

> An object is a member of the type Object. It is an unordered collection of properties each of which contains a primitive value, object, or function. A function stored in a property of an object is called a method.

([src](http://stackoverflow.com/a/5525820/493756))

Neither does `for .. in` 

> he for..in statement iterates over the enumerable properties of an object, in arbitrary order. For each distinct property, statements can be executed.

([src](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in))

**Comment by akhoury** [comment]
All the cool kids are doing it,

Handlebars' way
```
{{#each object}}
  {{@key}}: {{this}}
{{/each}}
```
([src](http://handlebarsjs.com/builtin_helpers.html#iteration ); scroll down to the end of this section)

**Comment by psychobunny** [comment]
Well if all the cool kids are doing it, guess we should too.. ;) 

Tests are passing but not pushing this to NodeBB just yet

**Comment by jongarrison** [comment]
Is this mentioned in the template system docs anywhere?  Is there an example of this working in a tpl?  I haven't been able to find one.

Thanks!

**Comment by akhoury** [comment]
I guess it's something like

```
<!-- BEGIN package -->
  @key: is @value
<!-- END package -->
```

[link](https://raw.githubusercontent.com/psychobunny/templates.js/496ed61d62944d03362252975bc8930bfc68d3a7/tests/templates/issue19b.tpl)

**Comment by julianlam** [comment]
Yes, that is correct.

**Comment by jongarrison** [comment]
Thanks and Thanks

**Comment by jongarrison** [comment]
Is it possible to use @key in conjunction with a template helper function inside a loop?

maybe like this?
{function.templateHelperFunction(@key)}

it appears right now that as I try a template helper function inside a template loop, that the @value is being passed in automatically, which may not be the most useful thing.

**Comment by julianlam** [comment]
`@key` being the index, yes? In that case I'd recommend using a helper to process the loop instead of `BEGIN..END`.
