### ISSUE TITLE
Referring to properties at root level returns wrong value

### ISSUE THREAD

**Issue by julianlam** [psychobunny/templates.js#29]
Given the following data

``` json
{
  "name": "foobar",
  "template": {
    "name": "bazquux"
  }
}
```

A corresponding template would have `bazquux` in place of `{name}` instead of `foobar`, as expected.

If `template.name` is not present, `{name}` is set to `foobar`.

**Comment by psychobunny** [comment]
Please submit breaking test case :trollface:

**Comment by psychobunny** [comment]
Managed to repro again, opening
