### ISSUE TITLE
Getting postMessage errors in console

### ISSUE THREAD

**Issue by FokkeZB** [psychobunny/templates.js#31]
Since a few days I can't save any forms in the NodeBB admin anymore and I think it might relate to an error I see in the console:

```
Uncaught SyntaxError: Failed to execute 'postMessage' on 'Window': Invalid target origin '' in a call to 'postMessage'.nodebb.min.js:18086 (anonymous function)
```

This traces back to https://github.com/psychobunny/templates.js/blob/master/lib/templates.js#L29

![screen shot 2015-03-18 at 13 42 17](https://cloud.githubusercontent.com/assets/2699409/6708888/ad751ebe-cd74-11e4-8c58-4c680bdbb510.png)

I have no idea why this errors... any idea?

**Comment by FokkeZB** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage the second argument for the target is indeed required (but can be `*` for no preference).

**Comment by psychobunny** [comment]
This is odd, you shouldn't be getting this error because we haven't activated web workers on NodeBB core just yet (it's being developed on a separate branch)

What's your core revision, tjs version and are you potentially using webworkers elsewhere? Thanks

**Comment by FokkeZB** [comment]
I use 0.6.1 which has ^0.1.15 for tjs and I haven't enabled any plugins.

**Comment by psychobunny** [comment]
Does adding `*` solve the issue for you? I would say upgrade to latest but that is no longer compatible with NodeBB 0.6x (my mistake, I should have published a new major version shortly after)

You could even just remove the web workers code altogether - it isn't slated for NodeBB core until post - 0.7.x

Let me know if you figure it out / need a hand

**Comment by FokkeZB** [comment]
Adding `*` removes the warning but I still have lots of issues with sockets somehow. Forms in the web admin (like editing category titles) don't submit and if I trace it I can see it's in some kind of loop where the above also is part of.

How do I remove these web workers? And how do they end up enabled while I'm using 0.6.1, which is supposed to be stable right? Should I use  different version?

**Comment by psychobunny** [comment]
I looked it up and you can safely downgrade to templates.js@0.1.2 (pre-webworker commits), I'll also update the NodeBB 0.6x core shrinkwrap to reflect this. 

Hope this fixes it for you, also out of curiosity can you provide your NodeBB's revision: `git rev-parse head` so I can try to see what's going on. Thanks!

**Comment by FokkeZB** [comment]
Thanks: 4648c0470d888b25c48b3252bf59b0c7724d73e9

**Comment by FokkeZB** [comment]
Maybe the problem is that I didn't use the shrinkwrap because I have it running on Node.ACS (a cloud by Appcelerator) which I need to prepare all plugins local for. I can't do install via webadmin.

**Comment by psychobunny** [comment]
Hope it works for you now. We've downgraded the 0.6x shrinkwrap tjs to 0.1.2: https://github.com/NodeBB/NodeBB/tree/v0.6.x

Let me know if you are still running into any issues. thanks

**Comment by FokkeZB** [comment]
Yes, this does fix the error in the console. The other web socket errors I he were related to running a cluster and handshakes failing because of that. Fixing that by makingn them stick.
