### ISSUE TITLE
self.postMessage needs two arguments, not one

### ISSUE THREAD

**Issue by julianlam** [psychobunny/templates.js#34]
Getting this error on client-side:

`Uncaught SyntaxError: Failed to execute 'postMessage' on 'Window': Invalid target origin '' in a call to 'postMessage'.`

I *don't* get it on local, but it does happen on a hosted instance we manage.

### [Probably also relevant](https://github.com/psychobunny/templates.js/blob/master/lib/templates.js#L60-L65)

[MDN suggests the method needs two parameters, not one](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage)

**Comment by MegaGM** [comment]
I don't catch it on https://community.nodebb.org/ but get it on all my forums
![](http://i.imgur.com/2IRZWha.png)

**Comment by julianlam** [comment]
Really weird, I haven't narrowed it down to the circumstances in which this message appears

**Comment by MegaGM** [comment]
Linux, Google Chrome 42.0.2311.90 ![](http://www.messentools.com/images/emoticones/zorrito/www.MessenTools.com-34%20pensativo.gif)
