### ISSUE TITLE
[[]] - multiline? 

### ISSUE THREAD

**Issue by NicolasSiver** [psychobunny/templates.js#36]
Would be great to have multiline support for `[[ ]]` constructions.

In current realisation, such presentation does not work:

```js
    [[global:last_edited_by_ago,
    <strong><a href="{relative_path}/user/{posts.editor.userslug}">{posts.editor.username}</a></strong>,
    <span class="timeago" title="{posts.relativeEditTime}"></span>]]
```

**Comment by pitaj** [comment]
The `[[ ]]` are not part of **templates.js**, they are part of the translation system used in NodeBB.

https://github.com/NodeBB/NodeBB/blob/master/public/src/modules/translator.js

**Comment by psychobunny** [comment]
https://github.com/NodeBB/NodeBB/commit/5ff9a7f9a9fad7d3e92826755603b6803bb60076
