### ISSUE TITLE
Don't break semantic versioning

### ISSUE THREAD

**Issue by pitaj** [psychobunny/templates.js#37]
You made a breaking change in 0.2.3, and you should then modify the major version or at least the minor version to display that. 

Thats means either 1.0.0 or 0.3.0

Obey the semver pls :smile:

**Comment by psychobunny** [comment]
0.2.3 was just a bugfix, 0.2.2 and 0.2.1 were some code cleanup/optimizations. Nothing breaking since the push to 0.2.0 (#22) about a week and a half ago?

**Comment by pitaj** [comment]
What commit was the change to escaping `{ thing }`?

**Comment by psychobunny** [comment]
Shortly before the bump from 0.1.x to 0.2.0. Basically both #11 and #22 broke enough things in NodeBB to justify the minor version bump

**Comment by pitaj** [comment]
Oh, never mind then.
