### ISSUE TITLE
How to draw grid with templates.js?

### ISSUE THREAD

**Issue by NicolasSiver** [psychobunny/templates.js#47]
Create lists is easy:

```
    <!-- BEGIN users -->
    <div class="row">
        <div class="col-md-12">
            //SOME USER
        </div>
    </div>
    <!-- END users -->
```

But what if I want to draw users as a grid? For example 3 columns (so bootstrap class will be `col-md-4`)

**Comment by psychobunny** [comment]
```
    <div class="row">
       <!-- BEGIN users -->
        <div class="col-md-4">
            //SOME USER
        </div>
        <!-- END users -->
    </div>
```

Does this work?

**Comment by NicolasSiver** [comment]
What do you mean? I have provided just a pseudocode. Lists are easy by using iteration over array.

**Comment by psychobunny** [comment]
Hmm perhaps I misunderstood then. Can you provide the resulting HTML so I can understand what you mean?
