### ISSUE TITLE
Does templates.js provide 'include' directive or something alike?

### ISSUE THREAD

**Issue by jiangcaiyang** [psychobunny/templates.js#48]
I'm using templates.js to provide plugins inside NodeBB.
Some html elements could make it reusable.
Like this:
{% include 'include/footer.html' %}
I know "swig.js" can.

**Comment by psychobunny** [comment]
`<!-- IMPORT include/footer.tpl -->`

Should work ;) We use it in NodeBB quite a lot feel free to check out the source of persona, lavendar, or vanilla for examples

**Comment by psychobunny** [comment]
Ex. https://github.com/NodeBB/nodebb-theme-persona/blob/master/templates/category.tpl#L2

**Comment by jiangcaiyang** [comment]
Okay, thanks, worked for me.

**Comment by psychobunny** [comment]
:+1:
