### ISSUE TITLE
How to load layout or block like jade (include, block) ?

### ISSUE THREAD

**Issue by labac1603** [psychobunny/templates.js#53]
I'm beginning to templates.js , 
How to load layout or block like jade (include, block) ?
i use expressjs

**Comment by psychobunny** [comment]
In NodeBB (the parent project of this framework), it's `<!-- IMPORT path/to/filename.tpl -->`

Right now the import code is still in NodeBB core, which can be found here:
https://github.com/NodeBB/NodeBB/blob/master/src/meta/templates.js#L122-L135

I'm planning on removing it and putting it into this repo at some point, but until then maybe that code might be useful for you if you're using this in your own project.

I'll leave this open until I get the chance to get around to moving it into t.js core
